site_name: CDI Gage Analysis Workflow
theme:
  name: material
  # features:
  #   - navigation.instant
  palette:
    primary: custom
    accent: custom
  logo: images/USGS_Favicon.png
  favicon: images/USGS_Favicon.png
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Introduction: 00_intro.md
  - Notebook page: cdi_gage_analysis_notebook.ipynb
  # - Python file: lapis
  # - Background: 01_background.md

plugins:
  - mkdocs-jupyter